config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :members , controllers:{
    omniauth_callbacks: "members/omniauth_callbacks"
  }

  authenticated :member do
    root "main#home"
  end

  unauthenticated :member do
    root "main#unregistered"
  end
  get 'main/helper'
  post "/complete_register" , to: "members/omniauth_callbacks#complete_register"
  resources :accounts , as: :member , only:[:show,:update,:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable , :omniauth_providers => [:facebook]

   def self.from_omniauth(auth)
		where(provider: auth.provider , uid: auth.uid).first_or_create do |member|
			
			if auth.info
				member.email = auth.info.email
				member.name = auth.info.name
				member.image = auth.info.image
			end
			member.password = Devise.friendly_token[0,20]
		
		end
   end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	before_action :set_member , only:[:show,:update,:destroy]
	rescue_from ActiveRecord::RecordNotFound , with: :invalid_member

	def show
		
	end

	private
		def set_member
			@member = Member.find(params[:id])
		end

		def invalid_member
			redirect_to root_path , alert: "Usuario inexistente"
			logger.error "Usuario inexistente: #{params[:id]}"
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def resource
    @resource ||= Member.new
  end

  def resource_class
    :member
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    @post = Post.new
    @posts = Post.all.reverse
  end

  def unregistered
  end

  def helper
  end
end

app/controllers/members/omniauth_callbacks_controller.rb
class Members::OmniauthCallbacksController < ApplicationController

	def facebook
		session["devise.auth"] = request.env["omniauth.auth"]
		@member = Member.from_omniauth(session["devise.auth"])
		if @member.persisted?
			sign_in_and_redirect @member , event: :authentication
			return
		end
		render :edit
	end

	def failure
		redirect_to root_path , alert: "Funcion failure"
	end

	def complete_register
    @member = Member.from_omniauth(session["devise.auth"])
    if @member.update(member_params)
      sign_in_and_redirect @member, event: :authentication
    else
      render :edit
    end
	end

	private
		def member_params
			params.require(:member).permit(:name,:email,:username)
		end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.member_id = current_member.id
    respond_to do |format|
      if @post.save
        format.js {  }
        # format.html { redirect_to @post, notice: 'Post was successfully created.' }
        # format.json { render :show, status: :created, location: @post }
      else
        # format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :member_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/accounts/show.haml
%p=@member.username
%h1 Perfil de #{@member.username}
%h1=@member.email

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SN</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p><%= notice %></p>
  	<p><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/main/helper.html.haml
%h1 Main#helper
%p Find me in app/views/main/helper.html.haml

app/views/main/home.html.haml
%h1 Main#home
= render "posts/form"
= link_to "Cerrar sesion" , destroy_member_session_path , method: :delete
#posts
  = render @posts

app/views/main/unregistered.html.haml
%h1 Main#unregistered
%nav
  = link_to "Login" , new_member_session_path
  = link_to "Login with facebook" , "members/auth/facebook"

app/views/posts/_form.html.haml
= form_for @post , remote: true do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :body
    = f.text_field :body
  .actions
    = f.submit 'Save'

app/views/posts/_post.haml
-cache post do
  %p=post.body

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Body
      %th Member
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.body
        %td= post.member
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @post.body
%p
  %b Member:
  = @post.member

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path